# Generated by Django 5.2.7 on 2025-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('signature_request', 'Signature Request'), ('signature_sign', 'Signature Sign'), ('payment_process', 'Payment Process'), ('status_change', 'Status Change'), ('cache_clear', 'Cache Clear')], max_length=30),
        ),
    ]
