# Generated by Django 5.1 on 2025-10-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='docusign_envelope_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='docusign_signing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('expired', 'Expired'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]