# Generated by Django 5.2.7 on 2025-10-12 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('signature_request', 'Signature Request'), ('signature_sign', 'Signature Sign'), ('payment_process', 'Payment Process'), ('status_change', 'Status Change'), ('cache_clear', 'Cache Clear'), ('notification_sent', 'Notification Sent'), ('alert_created', 'Alert Created'), ('alert_resolved', 'Alert Resolved')], max_length=30),
        ),
        migrations.CreateModel(
            name='PincodeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('pending_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('available_vendors', models.PositiveIntegerField(default=0)),
                ('active_vendors', models.PositiveIntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(blank=True, null=True)),
                ('avg_completion_time_hours', models.FloatField(blank=True, null=True)),
                ('customer_satisfaction_avg', models.FloatField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_booking_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('high_demand_alert_sent', models.BooleanField(default=False)),
                ('low_vendor_alert_sent', models.BooleanField(default=False)),
                ('promotional_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'pincode'],
                'indexes': [models.Index(fields=['pincode', 'date'], name='core_pincod_pincode_2425b7_idx'), models.Index(fields=['total_bookings'], name='core_pincod_total_b_c81772_idx'), models.Index(fields=['available_vendors'], name='core_pincod_availab_e51a8f_idx')],
                'unique_together': {('pincode', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('booking_timeout', 'Booking Timeout'), ('pending_signature', 'Pending Signature'), ('payment_hold', 'Payment Hold'), ('low_vendor_count', 'Low Vendor Count'), ('high_demand', 'High Demand'), ('service_completion_reminder', 'Service Completion Reminder'), ('system_error', 'System Error')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
                ('related_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.signature')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'status'], name='core_busine_alert_t_d76f05_idx'), models.Index(fields=['severity', 'status'], name='core_busine_severit_29c138_idx'), models.Index(fields=['created_at'], name='core_busine_created_be6877_idx'), models.Index(fields=['assigned_to'], name='core_busine_assigne_62f852_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('otp', 'OTP Verification'), ('signature_request', 'Signature Request'), ('pincode_alert', 'Pincode Alert'), ('demand_notification', 'Demand Notification'), ('bonus_alert', 'Bonus Alert'), ('business_alert', 'Business Alert'), ('payment_hold', 'Payment Hold Alert'), ('booking_timeout', 'Booking Timeout'), ('pending_signature', 'Pending Signature Alert'), ('promotional', 'Promotional')], max_length=30)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket'), ('push', 'Push Notification')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'notification_type'], name='core_notifi_recipie_ff4fe8_idx'), models.Index(fields=['method', 'status'], name='core_notifi_method_486eae_idx'), models.Index(fields=['sent_at'], name='core_notifi_sent_at_a459f2_idx')],
            },
        ),
    ]
