# Generated by Django 5.1 on 2025-10-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_auditlog_action_address_dispute_earnings_and_more"),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name="dispute",
            name="evidence_notes",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="evidence_photos",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="resolution_notes",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="resolved_at",
        ),
        
        # Add new fields
        migrations.AddField(
            model_name="dispute",
            name="dispute_type",
            field=models.CharField(
                choices=[
                    ("service_quality", "Service Quality"),
                    ("payment_issue", "Payment Issue"),
                    ("signature_refusal", "Signature Refusal"),
                    ("vendor_behavior", "Vendor Behavior"),
                    ("customer_behavior", "Customer Behavior"),
                    ("booking_cancellation", "Booking Cancellation"),
                    ("other", "Other"),
                ],
                default="service_quality",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="customer_evidence",
            field=models.JSONField(
                blank=True, help_text="Customer's evidence including photos, documents", null=True
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="vendor_evidence",
            field=models.JSONField(
                blank=True, help_text="Vendor's evidence including photos, documents", null=True
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="assigned_mediator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mediated_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_evidence",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Refund or compensation amount",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="escalation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="core.signature",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        
        # Update status choices
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("investigating", "Under Investigation"),
                    ("mediation", "In Mediation"),
                    ("resolved", "Resolved"),
                    ("escalated", "Escalated"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        
        # Add new indexes
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "severity"], name="core_disput_status_7f9980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["dispute_type"], name="core_disput_dispute_8a2b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["assigned_mediator"], name="core_disput_assigne_9c4d52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["created_at"], name="core_disput_created_1e2f43_idx"
            ),
        ),
    ]