# Generated by Django 4.2.7 on 2025-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_dispute_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='ai_flag',
            field=models.BooleanField(default=False, help_text='AI detected suspicious application'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason for AI flag'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='flagged_at',
            field=models.DateTimeField(blank=True, help_text='When the application was flagged by AI', null=True),
        ),
    ]