# Generated by Django 4.2.7 on 2025-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendorapplication_ai_flag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('create', 'Create'),
                    ('update', 'Update'),
                    ('delete', 'Delete'),
                    ('login', 'Login'),
                    ('logout', 'Logout'),
                    ('signature_request', 'Signature Request'),
                    ('signature_sign', 'Signature Sign'),
                    ('payment_process', 'Payment Process'),
                    ('status_change', 'Status Change'),
                    ('cache_clear', 'Cache Clear'),
                    ('notification_sent', 'Notification Sent'),
                    ('alert_created', 'Alert Created'),
                    ('alert_resolved', 'Alert Resolved'),
                    ('dispute_created', 'Dispute Created'),
                    ('dispute_assigned', 'Dispute Assigned'),
                    ('dispute_resolved', 'Dispute Resolved'),
                    ('bonus_calculated', 'Bonus Calculated'),
                    ('bonus_approved', 'Bonus Approved'),
                    ('vendor_application_submitted', 'Vendor Application Submitted'),
                    ('vendor_application_reviewed', 'Vendor Application Reviewed'),
                    ('vendor_application_flagged', 'Vendor Application Flagged by AI'),
                    ('document_uploaded', 'Document Uploaded'),
                    ('chat_message_sent', 'Chat Message Sent'),
                ],
                max_length=30,
            ),
        ),
    ]